#
# Python modules below are needed to run tests and check results
#
name: rte_rrtmgp_test_noplots

dependencies:
  - conda-forge::python=3.9
  - conda-forge::netcdf4
  - conda-forge::xarray
  - conda-forge::dask
  - conda-forge::numpy
