extract_subset – RTE kernels
extract_subset Interface
4 statements
Source File
public interface extract_subset
Subsetting, meaning extracting some portion of the 3D domain
Calls
Contents
Module Procedures
extract_subset_dim1_3d extract_subset_dim2_4d extract_subset_absorption_tau
Module Procedures
public pure subroutine extract_subset_dim1_3d(ncol, nlay, ngpt, array_in, colS, colE, array_out) bind(C, name="0")
Extract a subset from the first dimension (normally columns) of a 3D field. Applicable to most variables e.g. tau, ssa, g
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
Array sizes
integer, intent(in) :: nlay
Array sizes
integer, intent(in) :: ngpt
Array sizes
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt) :: array_in
Array to subset
integer, intent(in) :: colS
Starting and ending index
integer, intent(in) :: colE
Starting and ending index
real(kind=wp), intent(out), dimension(colE-colS+1, nlay,ngpt) :: array_out
subset of the input array
public pure subroutine extract_subset_dim2_4d(nmom, ncol, nlay, ngpt, array_in, colS, colE, array_out) bind(C, name="0")
Extract a subset from the second dimension (normally columns) of a 4D field. Applicable to phase function moments, where the first dimension is the moment
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nmom
Array sizes
integer, intent(in) :: ncol
Array sizes
integer, intent(in) :: nlay
Array sizes
integer, intent(in) :: ngpt
Array sizes
real(kind=wp), intent(in), dimension(nmom,ncol,nlay,ngpt) :: array_in
Array to subset
integer, intent(in) :: colS
Starting and ending index
integer, intent(in) :: colE
Starting and ending index
real(kind=wp), intent(out), dimension(nmom,colE-colS+1, nlay,ngpt) :: array_out
subset of the input array
public pure subroutine extract_subset_absorption_tau(ncol, nlay, ngpt, tau_in, ssa_in, colS, colE, tau_out) bind(C, name="0")
Extract the absorption optical thickness
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
Array sizes
integer, intent(in) :: nlay
Array sizes
integer, intent(in) :: ngpt
Array sizes
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt) :: tau_in
Optical thickness, single scattering albedo
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt) :: ssa_in
Optical thickness, single scattering albedo
integer, intent(in) :: colS
Starting and ending index
integer, intent(in) :: colE
Starting and ending index
real(kind=wp), intent(out), dimension(colE-colS+1, nlay,ngpt) :: tau_out
absorption optical thickness subset
Call graph
extract_subset calls extract_subset_dim1_3d, extract_subset_dim2_4d, extract_subset_absorption_tau