zero_array – RTE kernels
zero_array Interface
3 statements
Source File
public interface zero_array
Efficiently set arrays to zero
Calls
Called by
Contents
Module Procedures
zero_array_1D zero_array_2D zero_array_3D zero_array_4D
Module Procedures
public subroutine zero_array_1D(ni, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
real(kind=wp), intent(out), dimension(ni) :: array
public subroutine zero_array_2D(ni, nj, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
real(kind=wp), intent(out), dimension(ni, nj) :: array
public subroutine zero_array_3D(ni, nj, nk, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
integer, intent(in) :: nk
real(kind=wp), intent(out), dimension(ni, nj, nk) :: array
public subroutine zero_array_4D(ni, nj, nk, nl, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
integer, intent(in) :: nk
integer, intent(in) :: nl
real(kind=wp), intent(out), dimension(ni, nj, nk, nl) :: array
Call graph
zero_array calls zero_array_1d, zero_array_2d, zero_array_4d, zero_array_3d
sw_solver_2stream calls zero_array