rte_lw – RTE-Fortran
rte_lw Function
168 statements
Source File
public function rte_lw(optical_props, sources, sfc_emis, fluxes, inc_flux, n_gauss_angles, use_2stream, lw_Ds, flux_up_Jac) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_arry), intent(in) :: optical_props
Set of optical properties as one or more arrays
type(ty_source_func_lw), intent(in) :: sources
Derived type with Planck source functions
real(kind=wp), intent(in), dimension(:,:) :: sfc_emis
emissivity at surface [] (nband, ncol)
class(ty_fluxes), intent(inout) :: fluxes
Dervied type for computing spectral integrals from g-point fluxes. Default computes broadband fluxes at all levels if output arrays are defined. Can be extended per user desires.
real(kind=wp), intent(in), optional dimension(:,:), target :: inc_flux
incident flux at domain top [W/m2] (ncol, ngpts)
integer, intent(in), optional :: n_gauss_angles
Number of angles used in Gaussian quadrature (max 3, no-scattering solution)
logical, intent(in), optional :: use_2stream
When 2-stream parameters (tau/ssa/g) are provided, use 2-stream methods Default is to use re-scaled longwave transport
real(kind=wp), intent(in), optional dimension(:,:) :: lw_Ds
User-specifed 1/cos of transport angle per col, g-point
real(kind=wp), intent(inout), optional dimension(:,:), target :: flux_up_Jac
surface temperature flux Jacobian [W/m2/K] (ncol, nlay+1)
Return Value character(len=128)
If empty, calculation was successful
Calls
Contents
None
Call graph
rte_lw calls extents_are, any_vals_less_than, lw_solver_noscat, any_vals_outside, zero_array, lw_solver_2stream