language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-19mode

notifications:
  recipients:
    - weppos@weppos.net

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
    - rvm: ruby-head

