# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RTE-RRTMGP
email: rrtmgp@aer.com
description: >- # this means to ignore newlines until "baseurl:"
  RTE+RRTMGP is a set of codes for computing radiative fluxes in
  planetary atmospheres. RRTMGP uses a k-distribution to provide an optical
  description (absorption and possibly Rayleigh optical depth) of the gaseous
  atmosphere, along with the relevant source functions, on a pre-determined
  spectral grid given temperatures, pressures, and gas concentration.
  RTE computes fluxes given spectrally-resolved optical descriptions and
  source functions.
baseurl: "/rte-rrtmgp" # the subpath of your site, e.g. /blog
url: "https://earth-system-radiation.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #jekyllrb
github_username: earth-system-radiation

# Build settings
theme: minima
header_pages:
  - explanations/index.md
  - how-tos/index.md
  - reference/index.md
  - tutorials/index.md
# remote_theme: rundocs/jekyll-rtd-theme
#   from https://github.com/jekyllrtdtheme/jekyll-rtd-theme/
#   May require new _config.yml? Example at https://github.com/darren1998s/darren1998s.github.io ?

mathjax: true

# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - ford_templates/
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
